backend:
  name: github
  repo: barrtmos/my_manual
  branch: main
  base_url: https://decap-oauth-render-478e.onrender.com
  auth_endpoint: auth

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "notes"
    label: "Notes"
    folder: "src/content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Structural"
        name: "structural"
        widget: "select"
        options:
          - "ЗАМЕТКИ"
          - "ДИАЛОГИ"
          - "ИНСТРУКЦИИ"
          - "СХЕМЫ"
          - "НА ЗАМЕТКУ"
      - label: "Topics"
        name: "topics"
        widget: "list"
        max: 1
        field:
          label: "Topic"
          name: "topic"
          widget: "select"
          options:
            - "ЛИНУКС"
            - "ГИТХАБ"
            - "ГИТ"
            - "VSC"
            - "БЭКЕНД"
            - "РНР"
            - "LARAVEL"
      - { label: "Draft", name: "draft", widget: "boolean", required: false, default: false }
      - { label: "Body", name: "body", widget: "markdown" }
